version: 0.2

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - echo Building...
      - npm build
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: build
